# Unique project key in SonarCloud
sonar.projectKey=cs4218-1_team3
sonar.organization=cs4218-1

# Optional: name and version in SonarCloud UI
#sonar.projectName=Team3
#sonar.projectVersion=1.0

# Source code location relative to this file
sonar.sources=.

# Source code encoding
sonar.sourceEncoding=UTF-8
