apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ecommerce-secure
type: Opaque
data:
  # Create these with: [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("yourvalue"))
  mongo-url: bW9uZ29kYitzcnY6Ly9lMDg5NTc4MDo3ZkNnZnVlVlN5R3o4SUZXQGNsdXN0ZXIwLmUyNm4xdnUubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw
  jwt-secret: SEdGSEdFQUQxMjEyNDMyMjQzMg==